# Site settings
title: Entangled
email: freddieboy@gmail.com
url: http://www.entangledapp.com
#baseurl: http://www.entangledapp.com
description: "Connecting two people forever."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#55DBFF'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/entangledapp

# Build settings
markdown: kramdown
permalink: pretty
